version: '2'
services:
    khushfinal-app:
        image: khushfinal
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://khushfinal-mysql:3306/khushfinal?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=khushfinal-elasticsearch:9300
        ports:
            - 8080:8080
    khushfinal-mysql:
        extends:
            file: mysql.yml
            service: khushfinal-mysql
    khushfinal-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: khushfinal-elasticsearch
